### ISSUE TITLE
Original Pixels treated as a 3x3 array when using Display Modes

### ISSUE THREAD

**Issue by Linkr2** [agg23/openfpga-pokemonmini#5]
### Version (or build number)

0.2.0

### Steps to reproduce

I’ve been testing the new display modes introduced in Analogue OS 2.0 with the Pokemon Mini core, and it seems to be treating each original pixel as a 3x3 array instead of as one big individual pixel when using pixel grids, I wonder if it is related to the Core’s internal scaling…

![IMG_6705](https://github.com/agg23/openfpga-pokemonmini/assets/16480192/4ac8adc8-3fc3-4c7d-9565-075a30c5be1c)

### Expected Behavior

I was expecting for each original pixel to act as an individual pixel when using Display Mode’s various pixel grids.

### Actual Behavior

Instead, each pixel is composed by 9 (3x3) sub pixels when applying a pixel grid by using the new Display Modes.

**Comment by agg23** [comment]
Unfortunately this is entirely controlled by the Pocket's firmware, and there's nothing to tweak core side to improve this. I assume they didn't intend for the filter to be used on such low resolution devices.

**Comment by HeyItsLollie** [comment]
I was about to submit this issue as well. Is there really nothing that can be done core-side? Performing a screenshot directly on Pocket seems to suggest that it has an internal 3× upscaler built-in. This is 288×192.
![f4cdccab-3843-4dd8-a666-2b978f2954e6](https://github.com/agg23/openfpga-pokemonmini/assets/30498581/c5fd967f-7fb0-45c8-a86c-f37e3695c22b)

**Comment by agg23** [comment]
288x192 is (one of) the native output resolutions of the ported core, with the other being 96x64 (which as discussed on Arduboy, was previously broken in the Analogue scaler). So I am not outputting manually 3x3 pixels at a time, and at the time of writing, the Analogue scaler would not properly handle the native 96x64 correctly.

I would certainly accept contributions to fix it, but I am not really interested in doing a bunch of work to handle this new feature on Analogue's side that really should be configurable, and not require such workarounds.

**Comment by HeyItsLollie** [comment]
The scaler problem, do you mean how Pocket originally didn't offer a way to do Integer scaling? I just mentioned on Arduboy, but this should be solved as of OS 2.0 - the "Normal" unfiltered display mode now has access to "Fit" and "Integer" scaling options.

If the ported core already includes a 96x64 resolution, is it possible to expose that as a toggleable option, or switch over to use it instead or something? I know you're not doing any manual scaling yourself - Integer scaling wasn't forced like it was in the Arduboy core, there's no extra black border or anything. But the ported core's 288x192 resolution is just a built-in 3X scaler, and it also doesn't cleanly scale to fill the Pocket's 1600-wide screen, so it's not really benefiting from the higher resolution anyway.
